name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  # Run workflow when pushing on main
  push: { branches: ["master"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Config
          config_display: large
          config_timezone: "Europe/Istanbul"

          # Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_repositories: yes
          plugin_repositories_forks: yes
          plugin_repositories_affiliations: owner

          plugin_languages: yes
          plugin_languages_indepth: yes
